const CREATE_ACCOUNT_REPOSITORY_TOKEN = Symbol('CreateAccountRepository')

const FIND_ACCOUNT_BY_PROVIDER_ID_REPOSITORY_TOKEN = Symbol(
  'FindAccountByProviderIdRepository',
)

const GITHUB_OAUTH_SERVICE_TOKEN = Symbol('GithubOAuthService')

export {
  CREATE_ACCOUNT_REPOSITORY_TOKEN,
  FIND_ACCOUNT_BY_PROVIDER_ID_REPOSITORY_TOKEN,
  GITHUB_OAUTH_SERVICE_TOKEN,
}
